[versions]
agp = "8.13.2"

hilt = "2.57.2"

kotlin = "2.2.21"
ksp = "2.3.2"

paging = "3.3.6"
pagingCompose = "3.4.0-alpha04"

roborazzi="1.52.0"
room="2.8.4"

[libraries]
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.12.1" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.10.0" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version = "2.10.0" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2025.12.00" }

androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-material3-expressive = { module = "androidx.xr.compose.material3:material3", version = "1.0.0-alpha13" }
androidx-material3-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-material3-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.9.6" }
androidx-navigation-runtime-android = { module = "androidx.navigation:navigation-runtime-android", version= "2.9.6" }

androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }

androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version = "3.3.0" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version = "3.3.0" }

compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version = "1.3.3" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version = "1.3.0" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.3.0" }

junit = { module = "junit:junit", version = "4.13.2" }

kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version = "2.0.0" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.2" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.10.2" }

mvi-android = { module = "com.buildkt.mvi:android", version = "0.1.2" }
mvi-annotation-processor = { module = "com.buildkt.mvi:annotation-processor", version = "0.1.3" }

preview-scanner-compose = { module = "io.github.sergio-sastre.ComposablePreviewScanner:android", version = "0.8.0" }
preview-scanner-roborazzi = { module = "io.github.takahirom.roborazzi:roborazzi-compose-preview-scanner-support", version.ref = "roborazzi" }

robolectric = { module = "org.robolectric:robolectric", version = "4.16" }

room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version = "1.10.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

convention-android-library = { id = "convention.android.library", version = "" }

hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "14.0.1" }

roborazzi = {id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
